[package]
name = "raytracer"
version = "0.1.0"
authors = ["Eric K <eric.koehli@mail.utoronto.ca>"]
edition = "2018"

default-run = "raytracer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.27"
